import * as validator from "@/utils/validator";
export const formItem = [
    {
        prop: "etl_job",
        label: "作业名称",
        type: "select",
        options: [],
    },
    {
        prop: "pro_name",
        label: "作业程序名称",
        type: "input",
    },
    {
        prop: "sub_sys_cd",
        label: "任务编号",
        type: "input",
    },
    {
        prop: "pro_type",
        label: "作业程序类型",
        type: "select",
        options: [],
    },
]

export const tableItem =[
    { prop: "tag", type: "selection", width: "70", align: "center" },
    { prop: "sub_sys_cd", type: "text", label: "任务编号" ,minWidth:'140'},
    { prop: "etl_job", type: "link", label: "作业名称" ,minWidth:'300'},
    { prop: "etl_job_desc", type: "text", label: "作业描述" ,minWidth:'280'},
    { prop: "job_datasource", type: "text", label: "作业数据来源" ,minWidth:'150'},
    { prop: "dispFreq", type: "text", label: "调度频率" ,width:'120'},
    { prop: "dispType", type: "text", label: "调度触发方式" ,minWidth:'150'},
    { prop: "jobEffFlag", type: "text", label: "作业有效标志" ,minWidth:'150'},
    { prop: "upd_time", type: "text", label: "定义时间" ,minWidth:'180'},
    { prop: "todayDisp", type: "text", label: "当天是否调度" ,width:'150'},
    {
        type: "operate",
        label: "操作",
        width: "200px",
        operateArr: [
            { label: "编辑", type: "edit" },
            { label: "删除", type: "del" },
        ],
    },
]
export const modelFormItems = [
    {
        conceal: 'true',
        tag: 'A',
        prop: "etl_sys_cd",
        label: "工程编号",
        placeholder: "工程编号",
        type: "input",
        disabled: true,
        span: 8,
    },
    {
        conceal: 'true',
        tag: 'A',
        prop: "sub_sys_id",
        label: "任务编号",
        placeholder: "任务编号",
        type: "select",
        disabled: false,
        span: 8,
        options:[],
    },
    {
        prop: "etl_job",
        tag: 'A',
        label: "作业名称",
        placeholder: "作业名称",
        type: "input",
        disabled: false,
        span: 8,
    },
    {
        prop: "etl_job_desc",
        tag: 'A',
        label: "作业描述",
        placeholder: "作业描述",
        type: "input",
        disabled: false,
        span: 8,
    },
    {
        prop: "pro_type",
        tag: 'A',
        label: "作业程序类型",
        placeholder: "作业程序类型",
        type: "select",
        disabled: false,
        span: 8,
        options:[],
    },
    {
        prop: "pro_dic",
        tag: 'A',
        label: "作业程序目录",
        placeholder: "作业程序目录",
        type: "input",
        disabled: false,
        span: 8,
    },
    {
        prop: "pro_name",
        tag: 'A',
        label: "作业程序名称",
        placeholder: "作业程序名称",
        type: "input",
        disabled: false,
        span: 8,
    },
    {
        prop: "pro_para",
        tag: 'A',
        label: "作业程序参数",
        placeholder: "多个参数使用@分割",
        type: "input",
        disabled: false,
        span: 8,
    },
    {
        prop: "log_dic",
        tag: 'A',
        label: "日志目录",
        placeholder: "日志目录",
        type: "input",
        disabled: false,
        span: 8,
    },
    {
        prop: "disp_freq",
        tag: 'A',
        label: "调度频率",
        placeholder: "调度频率",
        type: "select",
        disabled: false,
        span: 8,
        selectChang: 'dispFreq',
        options:[],
    },
    {
        prop: "exe_frequency",
        tag: 'F',
        label: "每隔(分)执行",
        placeholder: "每隔(分)执行",
        type: "input",
        disabled: false,
        conceal: 'false',
        span: 8,
    },
    {
        prop: "exe_num",
        label: "执行次数",
        tag: 'F',
        placeholder: "执行次数",
        type: "input",
        disabled: false,
        conceal: 'false',
        span: 8,
    },
    {
        prop: "star_time",
        label: "开始执行时间",
        tag: 'F',
        placeholder: "开始执行时间",
        type: "dateTime",
        disabled: false,
        conceal: 'false',
        valueFormat: 'yyyyMMdd HHmmss',
        span: 8,
    },
    {
        prop: "end_time",
        label: "结束执行时间",
        tag: 'F',
        placeholder: "结束执行时间",
        type: "dateTime",
        disabled: false,
        conceal: 'false',
        valueFormat: 'yyyyMMdd HHmmss',
        span: 8,
    },
    {
        prop: "disp_offset",
        label: "调度时间位移",
        tag: 'M,D,T',
        placeholder: "0",
        type: "input",
        disabled: false,
        span: 8,
    },
    {
        prop: "disp_type",
        label: "调度触发方式",
        tag: 'M,D,T',
        placeholder: "调度触发方式",
        type: "select",
        disabled: false,
        selectChang: 'dispType',
        span: 8,
        options:[],
    },
    {
        prop: "disp_time",
        tag: 'M,T',
        label: "调度触发时间",
        placeholder: "调度触发时间",
        type: "time",
        disabled: false,
        span: 8,
    },
    {
        prop: "job_priority",
        label: "作业优先级",
        tag: 'M,D,T',
        placeholder: "0",
        type: "input",
        disabled: false,
        content: '作业优先级设置的数字越大越优先执行',
        placement: 'right',
        span: 8,
    },
    {
        prop: "job_eff_flag",
        tag: 'A',
        label: "作业有效标志",
        placeholder: "作业有效标志",
        type: "select",
        disabled: false,
        span: 8,
        options:[],
    },
    {
        prop: "today_disp",
        tag: 'A',
        label: "当天是否调度",
        placeholder: "当天是否调度",
        type: "select",
        disabled: false,
        span: 8,
        options:[],
    },
    {
        prop: "pre_etl_sys_cd",
        tag: 'D',
        label: "上游工程名称",
        placeholder: "上游工程名称",
        type: "input",
        disabled: true,
        span: 8,
    },
    {
        prop: "pre_etl_job_ids",
        tag: 'D',
        label: "上游作业名",
        placeholder: "上游作业名",
        type: "select",
        multiple: true,
        collapseTags: true,
        disabled: false,
        span: 8,
        options:[],
    },
    {
        prop: "status",
        tag: 'D',
        label: "依赖是否有效",
        placeholder: "依赖是否有效",
        type: "select",
        disabled: false,
        span: 8,
        options:[],
    },
    {
        prop: "success_job",
        tag: 'A',
        label: "成功后续作业",
        placeholder: "成功后续作业路径",
        type: "input",
        disabled: false,
        content: '请写完整的可执行命令，如执行shell请输入sh /home/xx/ss.sh',
        placement: 'right',
        span: 8,
    },
    {
        prop: "fail_job",
        tag: 'A',
        label: "失败后续作业",
        placeholder: "失败后续作业路径",
        type: "input",
        disabled: false,
        content: '请写完整的可执行命令，如执行shell请输入sh /home/xx/ss.sh',
        placement: 'right',
        span: 8,
    },
    {
        prop: "job_datasource",
        tag: 'A',
        label: "作业数据来源",
        placeholder: "作业数据来源",
        type: "select",
        disabled: false,
        span: 8,
        options:[],
    },
    {
        prop: "comments",
        tag: 'A',
        label: "备注",
        placeholder: "请输入备注",
        type: "textarea",
        disabled: false,
        span: 24,
    },


]

export const modelFromRules = {
    etl_sys_cd: [{ required: true, message: "请输入工程编号", trigger: "blur" }],
    sub_sys_id: [{ required: true, message: "请输入任务编号", trigger: "blur" }],
    etl_job: [{ required: true, message: "请输入作业名称", trigger: "blur" }],
    // etl_job_desc: [{ required: true, message: "请输入作业描述", trigger: "blur" }],
    pro_type: [{ required: true, message: "请输入作业程序类型", trigger: "blur" }],
    pro_dic: [{ required: true, message: "请输入作业程序目录", trigger: "blur" }],
    pro_name: [{ required: true, message: "请输入调度频率", trigger: "blur" }],
    log_dic: [{ required: true, message: "请输入调度触发方式", trigger: "blur" }],
    disp_freq: [{ required: true, message: "请输入调度频率", trigger: "blur" }],
    disp_type: [{ required: true, message: "请输入调度触发方式", trigger: "blur" }],
    job_datasource: [{ required: true, message: "请输入作业数据来源", trigger: "blur" }],
    job_eff_flag: [{ required: true, message: "请输入作业有效标志", trigger: "blur" }],
    status: [{ required: true, message: "请输入作业有效标志", trigger: "blur" }],
    today_disp: [{ required: true, message: "请输入作业有效标志", trigger: "blur" }],
    star_time: [{ required: true, message: "请输入作业有效标志", trigger: "blur" }],
    end_time: [{ required: true, message: "请输入作业有效标志", trigger: "blur" }],

}
export const modelFormConfig = {
    labelWidth: "130px",
    inline: false,
    ref: "checkForm",
};
