//画板配置
export const dashboard = {
  id: null,
  title: "", //大屏标题
  width: 1920, // 大屏设计宽度
  height: 1080, // 大屏设计高度
  description: "", // 大屏描述
  backgroundColor: "#34506a", // 大屏背景色
  backgroundImage: "screen-bg1", // 大屏背景图片
  presetLine: [], // 辅助线
  presetLineVisible: true, // 辅助线是否显示
};
//柱形图数据
const widgetsBar = [
  {
    type: "widget-barchart",
    value: {
      setup: {
        background: "", // 背景色
        backgroundStyleBorderColor: "#000",
        backgroundStyleBorderType: "dashed",
        backgroundStyleBorderWidth: 0,
        backgroundStyleColor: "rgba(180, 180, 180, 0.2)",
        backgroundStyleOpacity: 100,
        backgroundStyleShadowBlur: 10,
        backgroundStyleShadowColor: "rgba(0, 0, 0, 0.5)",
        colorStyle: "same", // 颜色样式
        colorX: "#fff",
        colorY: "#fff",
        dataColor: "",
        distance: 5,
        fontSize: 14,
        fontSizeX: 14,
        fontSizeY: 14,
        fontWeight: "normal",
        hideX: true,
        isNoTitle: true,
        isShow: true,
        isShowBackground: true,
        isShowLegend: true,
        isShowSplitLineX: false,
        isShowSplitLineY: false,
        isShowY: true,
        lateralPosition: "center",
        layerName: "柱状图-城市总览",
        layoutFront: "horizontal",
        legendColor: "#fff",
        legendFontSize: 12,
        legendName: "",
        legendWidth: 15,
        lineColorX: "#fff",
        lineColorY: "#fff",
        lineWidthX: 1,
        lineWidthY: 1,
        longitudinalPosition: "top",
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 40,
        marginTop: 50,
        maxWidth: 10,
        maxY: "",
        minHeight: 0,
        nameColorX: "#fff",
        nameColorY: "#fff",
        nameFontSizeX: 14,
        nameFontSizeY: 14,
        nameX: "",
        percentSign: false,
        radius: 5,
        reversalX: false,
        reversalY: false,
        scale: false,
        splitLineColorX: "#fff",
        splitLineColorY: "#fff",
        splitLineWidthX: 1,
        splitLineWidthY: 1,
        splitNumberY: 0,
        stackStyle: "leftRight",
        subText: "",
        subTextColor: "#fff",
        subTextFontSize: 20,
        subTextFontStyle: "normal",
        subTextFontWeight: "normal",
        textAlign: "center",
        textAngleX: 0,
        textAngleY: 0,
        textColor: "#FFD700",
        textFontSize: 20,
        textFontStyle: "normal",
        textFontWeight: "normal",
        textInterval: 0,
        textNameY: "",
        textRowsNum: "14",
        textRowsBreakAuto: false,
        tipsColor: "#00FEFF",
        tipsFontSize: 16,
        titleText: "",
        verticalShow: false,
        widgetCode: "widget-barchart",
        widgetId: "1wvwcqi4yvj",
        customColor: [
          { color: "#ff7f50" },
          { color: "#87cefa" },
          { color: "#da70d6" },
          { color: "#32cd32" },
          { color: "#6495ed" },
          { color: "#76A5D5" },
          { color: "#427142" },
        ],
      }, // 配置项
      data: {
        chartType: "widget-barchart",
        chartProperties: { create_time: "xAxis", sum_nums: "bar" },
        chartData: [
          {
            create_time: "2023-05-05",
            sum_nums: 25,
          },
          {
            create_time: "2023-05-06",
            sum_nums: 35,
          },
          {
            create_time: "2023-05-07",
            sum_nums: 45,
          },
          {
            create_time: "2023-05-08",
            sum_nums: 12,
          },
          {
            create_time: "2023-05-09",
            sum_nums: 44,
          },
          {
            create_time: "2023-05-10",
            sum_nums: 27,
          },
        ],
      }, // 数据项
      position: {
        height: 340,
        width: 640,
        index: 0,
        left: 503.17,
        top: 674.58,
      }, // 位置项
    },
  },
];
//折线图数据
const widgetsLine = [
  {
    type: "widget-linechart",
    value: {
      setup: {
        area: true,
        areaThickness: 5,
        background: "",
        colorX: "#fff",
        colorY: "#fff",
        customColor: [{ color: "#34A39A" }],
        dataColor: "#fff",
        fontSize: 0,
        fontSizeX: 14,
        fontSizeY: 14,
        fontWeight: "normal",
        hideX: true,
        isNoTitle: false,
        isShow: false,
        isShowLegend: true,
        isShowSplitLineX: false,
        isShowSplitLineY: false,
        isShowY: true,
        lateralPosition: "left",
        layerName: "折线图",
        layoutFront: "",
        legendColor: "#fff",
        legendFontSize: 12,
        legendName: "",
        legendWidth: 12,
        lineColorX: "#fff",
        lineColorY: "#fff",
        lineWidth: 4,
        lineWidthX: 1,
        lineWidthY: 1,
        longitudinalPosition: "",
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 40,
        marginTop: 50,
        markPoint: true,
        nameColorX: "#fff",
        nameColorY: "#fff",
        nameFontSizeX: 14,
        nameFontSizeY: 14,
        nameX: "",
        percentSign: false,
        pointSize: 5,
        reversalX: false,
        reversalY: false,
        scale: false,
        smoothCurve: false,
        splitLineColorX: "#fff",
        splitLineColorY: "#fff",
        splitLineWidthX: 1,
        splitLineWidthY: 1,
        splitNumberY: 0,
        subText: "",
        subTextColor: "#fff",
        subTextFontSize: 20,
        subTextFontStyle: "normal",
        subTextFontWeight: "normal",
        symbol: "circle",
        textAlign: "center",
        textAngleX: 0,
        textAngleY: 0,
        textColor: "#fff",
        textFontSize: 20,
        textFontStyle: "normal",
        textFontWeight: "normal",
        textInterval: 0,
        textNameY: "",
        textRowsNum: "2",
        textRowsBreakAuto: false,
        tipsColor: "#00FEFF",
        tipsFontSize: 16,
        titleText: "",
        widgetCode: "widget-linechart",
        widgetId: "1zvzcqi4yvj",
      }, // 配置项
      data: {
        chartType: "widget-linechart",
        chartProperties: { month: "xAxis", data: "line" },
        chartData: [
          {
            month: "1",
            data: 1000,
          },
          {
            month: "2",
            data: 2229,
          },
          {
            month: "3",
            data: 3879,
          },
          {
            month: "4",
            data: 2379,
          },
          {
            month: "5",
            data: 3879,
          },
          {
            month: "6",
            data: 2379,
          },
          {
            month: "7",
            data: 2229,
          },
          {
            month: "8",
            data: 3879,
          },
          {
            month: "9",
            data: 4079,
          },
          {
            month: "10",
            data: 2379,
          },
        ],
      }, // 数据项
      position: {
        height: 256.08,
        index: 2,
        left: 1298.49,
        top: 764.49,
        width: 497.07,
      }, // 位置项
    },
  },
];
//饼图数据
const widgetsPie = [
  {
    type: "widget-piechart",
    value: {
      setup: {
        background: "",
        customColor: [
          { color: "#0CD2E6" },
          { color: "#00BFA5" },
          { color: "#FFC722" },
          { color: "#886EFF" },
          { color: "#008DEC" },
        ],
        dataColor: "",
        fontSize: 12,
        fontWeight: "normal",
        isNoTitle: false,
        isShow: false,
        isShowLegend: false,
        lateralPosition: "",
        layerName: "饼图",
        layoutFront: "",
        legendColor: "#fff",
        legendFontSize: 16,
        legendWidth: 15,
        longitudinalPosition: "",
        numberValue: true,
        percentage: false,
        piechartStyle: "shixin",
        subText: "",
        subTextColor: "",
        subTextFontSize: 12,
        subTextFontWeight: "normal",
        textAlign: "left",
        textColor: "#fff",
        textFontSize: 20,
        textFontWeight: "normal",
        tipsFontSize: 16,
        tipsColor: "#00FEFF",
        titleText: "订单",
        widgetCode: "widget-piechart",
        widgetId: "1pvpcqi4yvj",
      }, // 配置项
      data: {
        chartType: "widget-piechart",
        chartProperties: { name: "name", value: "value" },
        chartData: [
          {
            name: "搜索引擎",
            value: 1048,
          },
          {
            name: "直接访问",
            value: 735,
          },
          {
            name: "邮件营销",
            value: 580,
          },
          {
            name: "联盟广告",
            value: 484,
          },
          {
            name: "视频广告",
            value: 300,
          },
        ],
      }, //数据
      position: {
        height: 210.62,
        index: 3,
        left: 174.96,
        top: 683.36,
        width: 406.07,
      }, //位置
    },
  },
];
//表格数据
const widgetsTable = [
  {
    type: "widget-table",
    value: {
      setup: {
        bodyColor: "#fff",
        borderColor: "#fff",
        borderWidth: 1,
        delayTime: 500,
        dynamicAddTable: [
          { name: "排名", width: "50%", key: "sort" },
          { name: "姓名", width: "50%", key: "name" },
          { name: "销售额", width: "100%", key: "money" },
          { name: "完成情况", width: "50%", key: "wcqk" },
        ],
        effect: "topLoop",
        eventColor: "",
        fontSize: 16,
        headBackColor: "",
        headColor: "#FFF",
        interTime: 2500,
        isHeader: true,
        isLine: false,
        isRoll: true,
        layerName: "表格",
        oldColor: "",
        rowHeight: 50,
        scroll: 1,
        tableBgColor: "",
        textAlign: "center",
        vis: 5,
        widgetCode: "widget-table",
        widgetId: "1tvtcqi4yvj",
      },
      data: {
        chartType: "widget-table",
        chartData: [
          { money: "2598.3元", name: "XX门店", sort: "01", wcqk: "85%" },
          { money: "2598.3元", name: "XX门店", sort: "02", wcqk: "85%" },
          { money: "2598.3元", name: "XX门店", sort: "03", wcqk: "85%" },
          { money: "2598.3元", name: "XX门店", sort: "04", wcqk: "85%" },
          { money: "2598.3元", name: "XX门店", sort: "05", wcqk: "85%" },
          { money: "2598.3元", name: "XX门店", sort: "06", wcqk: "85%" },
          { money: "2598.3元", name: "XX门店", sort: "06", wcqk: "85%" },
        ],
      },
      position: {
        height: 298.48,
        index: 3,
        left: 901.65,
        top: 331.14,
        width: 440.84,
      },
    },
  },
];
//柱线图数据
const widgetsBarLine = [
  {
    type: "widget-barlinechart",
    value: {
      setup: {
        area: true,
        areaThickness: 9,
        background: "",
        colorX: "#fff",
        colorYLeft: "#fff",
        colorYRight: "#fff",
        customColor: [{ color: "#00F4FFFF" }, { color: "#19FFE9" }],
        distanceBar: 5,
        distanceLine: 5,
        fontSizeBar: 14,
        fontSizeLine: 14,
        fontSizeX: 14,
        fontSizeYLeft: 14,
        fontSizeYRight: 14,
        fontWeightBar: "normal",
        fontWeightLine: "normal",
        hideX: true,
        isNoTitle: true,
        isShowBar: false,
        isShowLegend: true,
        isShowLine: true,
        isShowSplitLineX: false,
        isShowSplitLineYLeft: false,
        isShowSplitLineYRight: false,
        isShowYLeft: false,
        isShowYRight: false,
        lateralPosition: "center",
        layerName: "柱线图",
        layoutFront: "horizontal",
        legendColor: "#fff",
        legendFontSize: 12,
        legendName: "",
        legendWidth: 12,
        lineColorX: "#fff",
        lineColorYLeft: "#fff",
        lineColorYRight: "#fff",
        lineWidth: 3,
        lineWidthX: 1,
        lineWidthYLeft: 1,
        lineWidthYRight: 1,
        lineYLeft: true,
        lineYRight: true,
        longitudinalPosition: "top",
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 40,
        marginTop: 50,
        markPoint: true,
        maxWidth: 22,
        minHeight: 0,
        nameColorX: "#1EB0DC",
        nameColorYLeft: "#fff",
        nameColorYRight: "#fff",
        nameFontSizeX: 14,
        nameFontSizeYLeft: 14,
        nameFontSizeYRight: 14,
        nameX: "",
        percentSignBar: false,
        percentSignLine: false,
        pointSize: 2,
        radius: 0,
        reversalX: false,
        smoothCurve: false,
        splitLineColorX: "#fff",
        splitLineColorYLeft: "#fff",
        splitLineColorYRight: "#fff",
        splitLineFontWidthYLeft: 1,
        splitLineFontWidthYRight: 1,
        splitLineWidthX: 1,
        splitNumberLeft: 0,
        splitNumberRight: 0,
        subText: "",
        subTextColor: "#fff",
        subTextColorBar: "#fff",
        subTextColorLine: "#19FFE9",
        subTextFontSize: 20,
        subTextFontStyle: "normal",
        subTextFontWeight: "normal",
        symbol: "circle",
        textAlign: "left",
        textAngleX: 0,
        textAngleYLeft: 0,
        textAngleYRight: 0,
        textColor: "#fff",
        textFontSize: 20,
        textFontStyle: "normal",
        textFontWeight: "normal",
        textInterval: 0,
        textNameYLeft: "",
        textNameYRight: "",
        textRowsBreakAuto: false,
        textRowsNum: "5",
        tickLineYLeft: true,
        tickLineYRight: true,
        tipsColor: "#00FEFF",
        tipsFontSize: 16,
        titleText: "",
        widgetCode: "widget-barlinechart",
        widgetId: "1BvBcqi4yvj",
      },
      data: {
        chartType: "widget-barlinechart",
        chartProperties: { month: "xAxis", value: "bar", data: "line" },
        chartData: [
          {
            month: "1月",
            value: 2.6,
            data: 2,
          },
          {
            month: "2月",
            value: 5.9,
            data: 2.2,
          },
          {
            month: "3月",
            value: 9,
            data: 3.3,
          },
          {
            month: "4月",
            value: 26.4,
            data: 4.5,
          },
          {
            month: "5月",
            value: 28.7,
            data: 6.3,
          },
          {
            month: "6月",
            value: 70.7,
            data: 10.2,
          },
          {
            month: "7月",
            value: 175.6,
            data: 20.3,
          },
        ],
      },
      position: {
        height: 265.2,
        index: 24,
        left: 1387.69,
        top: 146.63,
        width: 400,
      },
    },
  },
];
//文本型数据
const widgetsText = [
  {
    type: "widget-text",
    value: {
      setup: {
        background: "rgba(115,170,229,.0)",
        color: "#A5DBF7",
        fontSize: 60,
        fontWeight: "bold",
        layerName: "文本框",
        letterSpacing: 0,
        text: "文本类型数据",
        textAlign: "center",
        whiteSpace: false,
        widgetCode: "widget-text",
        widgetId: "2tvtcqi4yvj",
      },
      data: {
        chartType: "widget-text",
        chartData: "文本类型数据",
      },
      position: {
        height: 79.34,
        index: 5,
        left: 792.51,
        top: 180.16,
        width: 412.2,
      },
    },
  },
];
//边框和流光直线数据
const widgetsBorderLine = [
  {
    type: "widget-border",
    value: {
      setup: {
        layerName: "边框",
        showtype: "dv-border-Box-1",
        widgetCode: "widget-border",
        widgetId: "24f8a1vyeru",
      },
      position: {
        height: 378.86,
        index: 9,
        left: 129.48,
        top: 107.5,
        width: 525.94,
      },
    },
  },
  {
    type: "widget-decorate-flow-line",
    value: {
      setup: {
        layerName: "流光直线",
        background: "",
        lightColor: "#fff",
        flowDirection: "left",
        flowingLightSpeed: "medium",
        flowingLightRotationCenter: "center",
        rotationAngle: 0,
        widgetCode: "widget-decorate-flow-line",
      },
      position: {
        top: 297,
        left: 872,
        width: 400,
        height: 4,
      },
    },
  },
];
//柱形堆叠图
const widgetStackchart = [
  {
    type: "widget-stackchart",
    value: {
      setup: {
        background: "",
        backgroundStyleBorderColor: "#000",
        backgroundStyleBorderType: "dashed",
        backgroundStyleBorderWidth: 0,
        backgroundStyleColor: "rgba(180, 180, 180, 0.2)",
        backgroundStyleOpacity: 100,
        backgroundStyleShadowBlur: 10,
        backgroundStyleShadowColor: "rgba(0, 0, 0, 0.5)",
        colorX: "#fff",
        colorY: "#fff",
        customColor: [
          { color: "#ff7f50" },
          { color: "#87cefa" },
          { color: "#da70d6" },
          { color: "#32cd32" },
          { color: "#6495ed" },
          { color: "#72A8DD" },
          { color: "#AE7B69" },
        ],
        dataColor: "",
        fontSize: 14,
        fontSizeX: 14,
        fontSizeY: 14,
        fontWeight: "normal",
        hideX: true,
        isNoTitle: true,
        isShow: false,
        isShowBackground: true,
        isShowLegend: true,
        isShowSplitLineX: false,
        isShowSplitLineY: false,
        isShowY: true,
        lateralPosition: "center",
        layerName: "柱状堆叠图",
        layoutFront: "horizontal",
        legendColor: "#fff",
        legendFontSize: 12,
        legendName: "",
        legendWidth: 12,
        lineColorX: "#fff",
        lineColorY: "#fff",
        lineWidthX: 1,
        lineWidthY: 1,
        longitudinalPosition: "top",
        marginBottom: 10,
        marginLeft: 10,
        marginRight: 40,
        marginTop: 50,
        maxWidth: 20,
        maxY: "",
        minHeight: 0,
        nameColorX: "#fff",
        nameColorY: "#fff",
        nameFontSizeX: 14,
        nameFontSizeY: 14,
        nameX: "",
        percentSign: false,
        radius: 5,
        reversalX: false,
        reversalY: false,
        scale: false,
        splitLineColorX: "#fff",
        splitLineColorY: "#fff",
        splitLineWidthX: 1,
        splitLineWidthY: 1,
        splitNumberY: 0,
        stackStyle: "leftRight",
        subText: "",
        subTextColor: "#fff",
        subTextFontSize: 20,
        subTextFontStyle: "normal",
        subTextFontWeight: "normal",
        textAlign: "center",
        textAngleX: 0,
        textAngleY: 0,
        textColor: "#FFD700",
        textFontSize: 20,
        textFontStyle: "normal",
        textFontWeight: "normal",
        textInterval: 0,
        textNameY: "",
        textRowsNum: "14",
        textRowsBreakAuto: false,
        tipsColor: "#00FEFF",
        tipsFontSize: 16,
        titleText: "",
        verticalShow: false,
        widgetCode: "widgetBarStackChart",
        widgetId: "1esx1hq4dcf",
      },
      data: {
        chartType: "widget-stackchart",
        chartProperties: {
          city_name: "yAxis",
          create_time: "xAxis",
          sum_nums: "bar",
        },
        chartData: [
          {
            city_name: "北京",
            create_time: "2020-01-01",
            sum_nums: 100,
          },
          {
            city_name: "北京",
            create_time: "2020-01-02",
            sum_nums: 200,
          },
          {
            city_name: "北京",
            create_time: "2020-01-03",
            sum_nums: 300,
          },
          {
            city_name: "上海",
            create_time: "2020-01-01",
            sum_nums: 400,
          },
          {
            city_name: "上海",
            create_time: "2020-01-02",
            sum_nums: 500,
          },
          {
            city_name: "上海",
            create_time: "2020-01-03",
            sum_nums: 600,
          },
        ],
      },
      position: {
        left: 354.17,
        top: 694.1,
        width: 600,
        height: 300,
        index: 10,
      },
    },
  },
];
//玫瑰饼图
const widgetPieNightingaleRoseArea = [
  {
    type: "WidgetPieNightingaleRoseArea",
    value: {
      setup: {
        background: "",
        customColor: [
          { color: "#FF801C" },
          { color: "#F5FF46" },
          { color: "#00FE65" },
          { color: "#00FEFF" },
          { color: "#ffa800" },
        ],
        dataColor: "",
        fontSize: 12,
        fontWeight: "normal",
        isNoTitle: true,
        isShow: true,
        isShowLegend: false,
        lateralPosition: "",
        layerName: "南丁格尔玫瑰图",
        layoutFront: "",
        legendColor: "#fff",
        legendFontSize: 16,
        legendWidth: 15,
        longitudinalPosition: "",
        nightingleRosetype: "area",
        numberValue: false,
        percentage: false,
        subText: "",
        subTextColor: "",
        subTextFontSize: 12,
        subTextFontWeight: "normal",
        subTextFontStyle: "normal",
        textAlign: "left",
        textColor: "#fff",
        textFontSize: 20,
        textFontStyle: "normal",
        textFontWeight: "normal",
        tipsColor: "#00FEFF",
        tipsFontSize: 16,
        titleText: "",
        widgetCode: "WidgetPieNightingaleRoseArea",
        widgetId: "1pvtcqi4yvj",
      },
      data: {
        chartType: "WidgetPieNightingaleRoseArea",
        chartProperties: { name: "name", value: "value" },
        chartData: [
          {
            name: "雅江县",
            value: 1048,
          },
          {
            name: "道孚县",
            value: 735,
          },
          {
            name: "炉霍县",
            value: 580,
          },
          {
            name: "甘孜县",
            value: 484,
          },
          {
            name: "新龙县",
            value: 300,
          },
        ],
      },
      position: {
        height: 230.34,
        index: 11,
        left: 34.89,
        top: 483.4,
        width: 407.61,
      },
    },
  },
];
//矩形树图
const widgetTreemap = [
  {
    type: "widget-treemapchart",
    value: {
      setup: {
        layerName: "矩形树图",
        background: "",
        isNoTitle: true,
        titleText: "",
        textColor: "#FFD700",
        textFontSize: 20,
        textFontWeight: "normal",
        textFontStyle: "normal",
        textAlign: "center",
        subText: "",
        subTextColor: "rgba(30, 144, 255, 1)",
        subTextFontSize: 20,
        subTextFontWeight: "normal",
        subTextFontStyle: "normal",
        dataPosition: "inside",
        distance: 5,
        fontSize: 14,
        dataColor: "#fff",
        fontWeight: "normal",
        tipsFontSize: 16,
        tipsColor: "#00FEFF",
        marginLeft: 10,
        marginRight: 40,
        marginTop: 50,
        marginBottom: 10,
        customColor: [
          { color: "#ff7f50" },
          { color: "#87cefa" },
          { color: "#da70d6" },
          { color: "#32cd32" },
          { color: "#6495ed" },
        ],
      },
      data: [
        {
          name: "Alice",
          value: 21,
        },
        {
          name: "John",
          value: 20,
        },
        {
          name: "Marie",
          value: 18,
        },
        {
          name: "Peter",
          value: 23,
        },
      ],
      position: {
        left: 354.17,
        top: 694.1,
        width: 600,
        height: 300,
        index: 10,
      },
    },
  },
];
export const widgets = [];
export const widgersPreview = [...widgetTreemap];
export const layerIcon = [
  {
    type: "widget-barchart",
    icon: "iconfont icon-zhuzhuangtu",
  },
  {
    type: "widget-linechart",
    icon: "iconfont icon-zhexiantu",
  },
  {
    type: "widget-piechart",
    icon: "iconfont icon-bingtu",
  },
  {
    type: "widget-barlinechart",
    icon: "iconfont icon-zhuxiantu",
  },
  {
    type: "widget-border",
    icon: "el-icon-picture",
  },
  {
    type: "widget-decorate-flow-line",
    icon: "el-icon-picture",
  },
  {
    type: "widget-table",
    icon: "iconfont icon-biaoge",
  },
  {
    type: "widget-text",
    icon: "iconfont icon-wenben",
  },
  {
    type: "widget-scatterchart",
    icon: "iconfont icon-sandiantu",
  },
  {
    type: "widget-stackchart",
    icon: "iconfont icon-zhuzhuangduidietu",
  },
  {
    type: "WidgetPieNightingaleRoseArea",
    icon: "iconfont icon-meiguibingtu",
  },
  {
    type: "widgetLineStackChart",
    icon: "iconfont icon-zhexiantu1",
  },
  {
    type: "widgetBarLineStackChart",
    icon: "iconfont icon-zhuxiantu",
  },
  {
    type: "widget-treemapchart",
    icon: "iconfont icon-juxingshutu",
  },
  {
    type: "widget-barpolarchart",
    icon: "iconfont icon-jizuobiaotiaoxingduidietu",
  },
];
export const columnArr = [
  {
    type: "selection",
    width: 50,
    prop: "check",
  },
  { label: "序号", type: "index", width: "70" },
  { label: "组件名称", prop: "component_name", type: "text", minWidth: "120" },
  {
    label: "组件描述",
    prop: "component_desc",
    type: "text",
    minWidth: "120",
    fixed: "right",
  },
];
