const tokenItems = [
    {
        label: "用户名",
        prop: "user_id",
        type: "input",
        placeholder: "请输入用户名",
        span: 12,
    },
    {
        label: "密码",
        prop: "user_password",
        type: "input",
        placeholder: "请输入密码",
        span: 12,
    },
];
const dataItems = [
    {
        prop: "token",
        label: "token",
        placeholder: "请输入token",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "url",
        label: "url",
        placeholder: "请输入请求路径",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "tableName",
        label: "tableName",
        placeholder: "请输入系统登记表名称",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "dataType",
        label: "dataType",
        placeholder: "请输入输出数据类型",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "outType",
        label: "outType",
        placeholder: "请输入输出数据形式",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "num",
        label: "num",
        placeholder: "请输入显示条数",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "selectColumn",
        label: "selectColumn",
        placeholder: "请输入需要查询的列名",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "whereColumn",
        label: "whereColumn",
        placeholder: "请输入查询条件",
        type: "input",
        disabled: false,
        span: 24,
    }, {
        prop: "ds_name",
        label: "ds_name",
        placeholder: "请输入数据源名称",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "agent_name",
        label: "agent_name",
        placeholder: "请输入agent采集名称",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "fcs_name",
        label: "fcs_name",
        placeholder: "请输入任务采集名称",
        type: "input",
        disabled: false,
        span: 24,
    }, {
        prop: "filename",
        label: "filename",
        placeholder: "请输入查询文件名",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "filesize",
        label: "filesize",
        placeholder: "请输入文件大小",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "filesuffix",
        label: "filesuffix",
        placeholder: "请输入文件后缀名",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "filemd5",
        label: "filemd5",
        placeholder: "请输入文件md5值",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "filepath",
        label: "filepath",
        placeholder: "请输入文件路径",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "storagedate",
        label: "storagedate",
        placeholder: "请输入文件入库日期",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "sql",
        label: "sql",
        placeholder: "请输入要执行的sql语句",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "query",
        label: "query",
        placeholder: "请输入检索信息",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "dep_id",
        label: "dep_id",
        placeholder: "请输入部门ID",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "fcs_id",
        label: "fcs_id",
        placeholder: "请输入任务ID",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "asynType",
        label: "asynType",
        placeholder: "请输入是否异步",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "directory",
        label: "directory",
        placeholder: "请输入文件目录",
        type: "input",
        disabled: false,
        span: 24,
    },{
        prop: "uuid",
        label: "uuid",
        placeholder: "请输入uuid",
        type: "input",
        disabled: false,
        span: 24,
    },
];
const tokenItemsConfig = {
    labelWidth: "100px",
    inline: false,
    ref: "checkTokenForm",
};
const dataItemsConfig = {
    labelWidth: "100px",
    inline: false,
    ref: "checkForm",
};

export {tokenItems,dataItems,dataItemsConfig,tokenItemsConfig}
